USERNAME_FIELD='//*[@id="user-name"]'
PASSWORD_FIELD='//*[@id="password"]'
LOGIN_BUTTON='//*[@id="login-button"]'
TITLE_TEXT='//*[@class="app_logo"]'
MENU_BUTTON='//*[@id="react-burger-menu-btn"]'
LOGOUT_BUTTON='//*[@id="logout_sidebar_link"]'
ADD_BACKPACK_BTN='//*[@id="add-to-cart-sauce-labs-backpack"]'
CART_LINK='//*[@class="shopping_cart_link"]'
PRODUCT_NAME='//*[@class="inventory_item_name"]'
CART_ITEM='//*[@class="cart_item"]'
REMOVE_PRODUCT_BUTTON='//*[@id="remove-sauce-labs-backpack"]'
ERROR_MESSAGE='//*[@class="error-message-container error"]'